# Generated by Django 4.2.4 on 2024-02-02 13:16

import app.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logoimage/')),
                ('title', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('DepartmentRegistrationNo', models.CharField(max_length=150)),
                ('contactNo', models.CharField(max_length=15)),
                ('editor', models.CharField(max_length=200)),
                ('adEmail', models.EmailField(max_length=254)),
                ('facebookUrl', models.URLField(blank=True, null=True)),
                ('twitterUrl', models.URLField(blank=True, null=True)),
                ('youtubeUrl', models.URLField(blank=True, null=True)),
                ('instaUrl', models.URLField(blank=True, null=True)),
                ('tiktokUrl', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DigitalMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='digitalMarketing')),
                ('description', ckeditor.fields.RichTextField()),
                ('previousPrice', models.PositiveIntegerField()),
                ('currentPrice', models.PositiveIntegerField()),
                ('ordering', models.PositiveIntegerField()),
                ('marketing_slug', app.models.CustomAutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorizontalAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='horizontalads/')),
                ('url', models.URLField(blank=True, null=True)),
                ('positionNumber', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('six', 'Six')], max_length=150)),
                ('page', models.CharField(choices=[('home_page', 'Home Page'), ('news_details', 'News Detail')], default='home_page', max_length=150)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MainCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_name', models.CharField(max_length=150)),
                ('main_ctg_slug', app.models.CustomAutoSlugField(default=None, editable=False, populate_from='categorie_name', unique=True)),
                ('icons', models.ImageField(upload_to='categorieIcons/')),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('ordering', models.PositiveIntegerField()),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PopUpAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='popads/')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('privacy_policy', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('videoUrl', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategorie_name', models.CharField(max_length=150)),
                ('subctgslug', app.models.CustomAutoSlugField(default=None, editable=False, populate_from='subcategorie_name', unique=True)),
                ('ordering', models.PositiveIntegerField()),
                ('maincategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='app.maincategorie')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='newsimage/')),
                ('discriptions', ckeditor.fields.RichTextField()),
                ('news_slug', app.models.CustomAutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('trending', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainCtg', to='app.maincategorie')),
                ('subCategorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCtg', to='app.subcategorie')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-id'],
            },
        ),
    ]
